---
name: BaksonDeploy

on:
  - push

jobs:

  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
